//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 05:31:55 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://giraudev.com/spring-soap-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.giraudev.spring_soap_example;
